---
name: Bitcoin
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2204
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for project
        run: pip3 install ansible molecule[docker] docker

      - name: Test with molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: {{ matrix.distro }}
